In [2]:
name = "Ameer"
other_name = name

print(name)
print(other_name)

name = "John"
other_name = name
print(name)
print(other_name)

Ameer
Ameer
John
John


In [3]:
lst = ['zack', 'zebra']
max(lst)

'zebra'

In [6]:
import numpy as np
np.eye((4),dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]
